#!/usr/bin/env bash
# Script that copies a file from a client to a server

# Check if the number of arguments provided is less than 3
if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
# If the number of arguments is less than 4, use SSH without a specific key
elif [ "$#" -lt 4 ]
then
    # Copy the file to the server using SCP without specifying a SSH key
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
# If the number of arguments is 4 or more, use SCP with a specific SSH key
else
    # Copy the file to the server using SCP with the specified SSH key
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
