#!/usr/bin/env bash

# configures a server to listening on port 80 of all server's active IPv4 IPs

# Change the listening port from 8080 to 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
# Restart the nginx service
sudo service nginx restart
