#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user "ubunty"

# Define the server address
server_address="52.73.34.195"

# SSH connection command using single-character flags
ssh ubuntu@"$server_address" -i ~/.ssh/school
